// app/api/resumes/[id]/export/route.ts

// Force Node — pdfkit does NOT work on Edge
export const runtime = "nodejs";
export const dynamic = "force-dynamic";

import { NextResponse } from "next/server";
import { and, eq } from "drizzle-orm";
import { db } from "@/config/db";
import { resumes, users } from "@/config/schema";
import { requireUser } from "@/lib/auth";

function safeFilename(s: string | null | undefined) {
  return (s || "resume")
    .replace(/[\/\\?%*:|"<>]/g, "-")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 80);
}

export async function GET(
  _req: Request,
  ctx: { params: Promise<{ id: string }> }
) {
  // ✅ Next 15: params is a Promise
  const { id } = await ctx.params;

  try {
    // 1) Auth + tenancy
    const { email } = await requireUser();
    const me = await db.query.users.findFirst({ where: eq(users.email, email) });
    if (!me) return NextResponse.json({ error: "User not found" }, { status: 404 });

    const row = await db.query.resumes.findFirst({
      where: and(eq(resumes.id, id), eq(resumes.userId, me.id)),
    });
    if (!row) return NextResponse.json({ error: "Resume not found" }, { status: 404 });

    // 2) Use STANDALONE pdfkit (bundled fonts). Type as any to avoid TS declarations.
    const pdfkitStandalone: any = await import("pdfkit/js/pdfkit.standalone.js");
    const PDFDocument: any = pdfkitStandalone.default ?? pdfkitStandalone;

    // 3) Build PDF into a Buffer (works reliably on Node 18+)
    const chunks: Buffer[] = [];
    const doc = new PDFDocument({ size: "A4", margin: 50 });

    // Collect binary data
    doc.on("data", (c: Buffer) => chunks.push(c));
    const ended = new Promise<void>((resolve, reject) => {
      doc.on("end", () => resolve());
      doc.on("error", (e: unknown) =>
        reject(e instanceof Error ? e : new Error(String(e)))
      );
    });

    // ---- Minimal content (replace with your real template) ----
    doc.fontSize(22).text(row.title || "Resume", { align: "left" });
    doc.moveDown(0.5);
    doc.fontSize(12).fillColor("#666").text(`Template: ${row.template ?? "—"}`);
    doc.moveDown();
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#ccc").stroke();
    doc.moveDown();
    doc.fillColor("#000").fontSize(12).text(
      "This is a placeholder PDF generated by PDFKit (standalone). Replace with your real resume content."
    );
    // ----------------------------------------------------------

    doc.end();
    await ended;

    const pdf = Buffer.concat(chunks);
    const filename = `${safeFilename(row.title)}.pdf`;

    return new NextResponse(pdf, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `inline; filename="${filename}"`,
        "Cache-Control": "no-store",
        "Content-Length": String(pdf.length),
      },
    });
  } catch (err: any) {
    console.error("[/api/resumes/:id/export] error:", err?.stack || err);
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
  }
}
